import "@/shared/styles/index.css.ts";
import { rootStyle } from "@/shared/styles/global.css";
import type { Metadata } from "next";
import "@/shared/styles/global.css";
import QueryProvider from "@/shared/utils/query-provider";
import { SPRITE } from "@/shared/constants/sprite";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

function SvgSpriteInjector() {
  return (
    <div
      aria-hidden
      style={{
        position: "absolute",
        width: 0,
        height: 0,
        overflow: "hidden",
      }}
      dangerouslySetInnerHTML={{ __html: SPRITE }}
    />
  );
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ko">
      <body>
        <SvgSpriteInjector />

        <div className={rootStyle}>
          <QueryProvider>{children}</QueryProvider>
        </div>
      </body>
    </html>
  );
}
