export const ICONS = [
  "alarm",
  "apple",
  "arrow-right",
  "check-circle",
  "check-mark",
  "chevron",
  "edit",
  "file",
  "file-text",
  "graph-active",
  "graph-default",
  "home",
  "home-active",
  "kakao",
  "log-out",
  "message-square",
  "minus",
  "multiple",
  "note-active",
  "note-default",
  "plus",
  "search",
  "star",
  "user"
] as const;
export type IconName = (typeof ICONS)[number];
